### ISSUE TITLE
Great Job! Installation Challenges

### ISSUE THREAD

**Issue by BBeretta** [DarkNeos/neos-ts#18]
Hello everyone! How are you doing?
Great job, guys! I'm really digging it, and the web languages are awesome! 🚀

I cloned it to see if I can try to contribute (maybe translate it into English, create a new format, like Speed Duel, different from Duel Links).

I ran the installation commands for the packages (npm), installed Rust, ran the npm run dev command, and it was smooth sailing until these errors popped up:

```
error: linking with `rust-lld` failed: exit code: 1
error: could not compile `rust-src` (lib) due to 1 previous error
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
```
  
But I'm facing a challenge installing the environment right now (specifically Rust).
If possible, is there any document that explains step-by-step how to set up the environments?

Thanks a bunch for your time, and keep up the awesome work! 🙌

**Comment by SKTT1Ryze** [comment]
Hello, my friend. Thank you very much for your attention.
Maybe you miss the `WebAssembly` toolchain, which is one of the dependencies of this project.
You can try the following steps to fix the errors:
```
curl --proto '=https' --tlsv1.2 -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh
```

And the [.gitlab-ci.yml](https://github.com/DarkNeos/neos-ts/blob/main/.gitlab-ci.yml) may help you to find step-by-step guide to set up the environments.

By the way, I'm very happy to see that some foreign friends to contribute to our project, but it's a pity that all of comments in this project are written in Chinese currently, which maybe lead to difficulty of understanding the code. I would spend some time adding English comments soon, and if you have any questions about the architecture of this project or the implementation details, feel free to create issue and tell me.

Finally, we develop and deploy our project in the `GitLab` instead of `Github`, so when you are ready to contribute, please create `Merge Request` in the repo in `GitLab`: https://code.mycard.moe/mycard/Neos.

Best wishes for you.

**Comment by BBeretta** [comment]
Hey my friend!! 
Thank you for the answer quickly!
I'll check here and update you soon!!

**Comment by BBeretta** [comment]
Heey!! Worked 100% ! Thank you!!
